# coding=utf-8

stoplist = [u'a', u'aby', u'ach', u'acz', u'aczkolwiek', u'aj', u'albo', u'ale', u'ależ', u'alez', u'ani', u'aż', u'az',
            u'bardziej', u'bardzo', u'bo', u'bowiem', u'by', u'byli', u'bynajmniej', u'być', u'byc', u'był', u'byl',
            u'była', u'byla', u'było', u'bylo', u'były', u'byly', u'będzie', u'bedzie', u'będą', u'beda', u'będa',
            u'bedą', u'cali', u'cała', u'cala', u'cały', u'caly', u'ci', u'cię', u'cie', u'ciebie', u'co', u'cokolwiek',
            u'coś', u'cos', u'czasami', u'czasem', u'czemu', u'czy', u'czyli', u'daleko', u'dla', u'dlaczego',
            u'dlatego', u'do', u'dobrze', u'dokąd', u'dokad', u'dość', u'dosc', u'dużo', u'duzo', u'dwa', u'dwaj',
            u'dwie', u'dwoje', u'dziś', u'dzis', u'dzisiaj', u'gdy', u'gdyby', u'gdyż', u'gdyz', u'gdzie',
            u'gdziekolwiek', u'gdzieś', u'gdzies', u'i', u'ich', u'ile', u'im', u'inna', u'inne', u'inny', u'innych',
            u'iż', u'iz', u'ja', u'ją', u'jak', u'jakaś', u'jakas', u'jakby', u'jaki', u'jakichś', u'jakichs', u'jakie',
            u'jakiś', u'jakis', u'jakiż', u'jakiz', u'jakkolwiek', u'jako', u'jakoś', u'jakos', u'je', u'jeden',
            u'jedna', u'jedno', u'jednak', u'jednakże', u'jednakze', u'jego', u'jej', u'jemu', u'jest', u'jestem',
            u'jeszcze', u'jeśli', u'jesli', u'jeżeli', u'jezeli', u'już', u'juz', u'każdy', u'kazdy', u'kiedy',
            u'kilka', u'kimś', u'kims', u'kto', u'ktokolwiek', u'ktoś', u'ktos', u'która', u'ktora', u'które', u'ktore',
            u'którego', u'ktorego', u'której', u'ktorej', u'który', u'ktory', u'których', u'ktorych', u'którym',
            u'ktorym', u'którzy', u'ktorzy', u'ku', u'lat', u'lecz', u'lub', u'ma', u'mają', u'mało', u'malo,' u'mam',
            u'mi', u'mimo', u'mną', u'mna', u'mnie', u'mogą', u'moga', u'moi', u'moim', u'moja', u'moje', u'może',
            u'moze', u'możliwe', u'mozliwe', u'można', u'mozna', u'mój', u'moj', u'mu', u'musi', u'my', u'nam', u'nami',
            u'nas', u'nasi', u'nasz', u'nasza', u'nasze', u'naszego', u'naszych', u'natomiast', u'natychmiast',
            u'nawet', u'nią', u'nia', u'nic', u'nich', u'nie', u'niech', u'niego', u'niej', u'niemu', u'nigdy', u'nim',
            u'nimi', u'niż', u'niz', u'no', u'o', u'od', u'około', u'okolo', u'on', u'ona', u'one', u'oni', u'ono',
            u'oraz', u'oto', u'owszem', u'pan', u'pana', u'pani', u'po', u'podczas', u'pomimo', u'ponieważ',
            u'poniewaz', u'powinien', u'powinna', u'powinni', u'powinno', u'prawie', u'przecież', u'przeciez',
            u'przede', u'przedtem', u'przez', u'roku', u'również', u'rowniez', u'sam', u'sama', u'są', u'sa', u'się',
            u'sie', u'skąd', u'skad', u'sobie', u'sobą', u'soba', u'sposób', u'sposob', u'swoje', u'ta', u'tak',
            u'taka', u'taki', u'takie', u'także', u'takze', u'tam', u'te', u'tego', u'tej', u'temu', u'ten', u'teraz',
            u'też', u'tez', u'to', u'tobą', u'toba', u'tobie', u'toteż', u'totez', u'trzeba', u'tu', u'tutaj', u'twoi',
            u'twoim', u'twoja', u'twoje', u'twym', u'twój', u'twoj', u'ty', u'tych', u'tylko', u'tym', u'u', u'wam',
            u'wami', u'was', u'wasz', u'wasza', u'wasze', u'według', u'wedlug', u'wiele', u'wielu', u'więc', u'wiec',
            u'więcej', u'wiecej', u'wszyscy', u'wszystkich', u'wszystkie', u'wszystkim', u'wszystko', u'wtedy',
            u'wy', u'właśnie', u'wlasnie', u'zapewne', u'zawsze', u'ze', u'zł', u'znowu', u'znów', u'znow', u'został',
            u'zostal', u'żaden', u'zaden', u'żadna', u'zadna' u'żadne', u'zadne', u'żadnych', u'zadnych', u'że',
            u'żeby', u'zeby']